# Local version of Docker compose, using environment variables passed in by env file
version: "3"

services:
  localstack:
    environment:
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
  web:
    env_file:
      - .env
