# Docker compose file intended to be used in CI/CD pipelines
version: "3"

services:
  web:
    environment:
      # Additional values passed in by the CircleCI host machine
      - ACR_VALUES=${ACR_VALUES}
      - BASE_URL=${BASE_URL}
      - CLIENT_ASSERTION_TYPE=${CLIENT_ASSERTION_TYPE}
      - CLIENT_ID=${CLIENT_ID}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - MOCK_TOKEN=${MOCK_TOKEN}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_ISSUER=${OIDC_OP_ISSUER}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - OIDC_OP_LOGOUT_ENDPOINT=${OIDC_OP_LOGOUT_ENDPOINT}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
