version: 2.1
orbs:
  node: circleci/node@4.2.1
commands:
  ###
  # General re-usable commands
  #
  cf-check:
    steps:
      - run:
          name: 'Ensure cf cli is installed, otherwise install it.'
          command: "./scripts/cf-check.sh"

  docker-compose-check:
    steps:
      - run:
          name: 'Ensure docker-compose exists,otherwise install it.'
          command: "./scripts/docker-compose-check.sh"

  install-nodejs:
    steps:
      - run:
          name: "Install Node.JS"
          command: |
            source /opt/circleci/.nvm/nvm.sh
            nvm install v12.18
            nvm alias default v12.18
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

  sudo-check:
    steps:
      - run:
          name: 'Ensure sudo is installed, otherwise install it.'
          command: "./scripts/sudo-check.sh"

  ###
  # Deployment commands
  #
  login-cloud-dot-gov:
    description: Authenticates with Cloud.gov and sets appropriate targets
    parameters:
      cf-password:
        type: env_var_name
        default: CF_PASSWORD_DEV
      cf-org:
        type: env_var_name
        default: CF_ORG
      cf-space:
        type: string
        default: tanf-dev
      cf-username:
        type: env_var_name
        default: CF_USERNAME_DEV
    steps:
      - run: |
          cf login -a https://api.fr.cloud.gov \
            -u ${<<parameters.cf-username>>} \
            -p ${<<parameters.cf-password>>} \
            -o ${<<parameters.cf-org>>} \
            -s <<parameters.cf-space>>

  deploy-frontend:
    parameters:
      deploy-strategy:
        default: "rolling"
        type: string
      backend-appname:
        default: "tdp-backend"
        type: string
      frontend-appname:
        default: "tdp-frontend"
        type: string

    steps:
      - node/install:
          install-yarn: true
          node-version: 12.18
      - run: |
          bash ./scripts/deploy-frontend.sh \
            <<parameters.deploy-strategy>> \
            <<parameters.frontend-appname>> \
            <<parameters.backend-appname>>

  deploy-backend:
    parameters:
      deploy-strategy:
        default: "rolling"
        type: string
      backend-appname:
        default: "tdp-backend"
        type: string
    steps:
      - run: |
          bash ./scripts/deploy-backend.sh \
            <<parameters.deploy-strategy>> \
            <<parameters.backend-appname>>

jobs:
  test-backend:
    machine:
      docker_layer_caching: false
    branches:
    steps:
      - checkout
      - docker-compose-check
      - run:
          name: "Test: Build and Spin-up Django API Service"
          command: "cd tdrs-backend; docker-compose up -d --build"
      - run:
          name: "Test: Run Unit Tests And Create Code Coverage Report"
          command: "cd tdrs-backend; docker-compose run --rm web bash -c \"pytest --cov-report=xml\""
      - run:
          name: "Upload Backend Coverage Report to CodeCov If On Target Branch"
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ] ; then
              cd tdrs-backend; bash <(curl -s https://codecov.io/bash)  -f ./coverage.xml -F main-backend
            elif [ "$CIRCLE_BRANCH" == "raft-tdp-main" ] ; then
              cd tdrs-backend; bash <(curl -s https://codecov.io/bash)  -f ./coverage.xml -F dev-backend
            fi
      - run:
          name:  "Test: Execute Python Linting Test"
          command: "cd tdrs-backend; docker-compose run --rm web bash -c \"flake8 .\""
      - run:
          name:  "Test: Execute Python OWASP ZAP Vulnerability Scan"
          command: "cd tdrs-backend; ./zap-scanner.sh"
      - store_artifacts:
          path: tdrs-backend/reports/owasp_report.html

  test-frontend:
    working_directory: ~/tdp-apps
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - docker-compose-check
      - install-nodejs
      - node/install-yarn
      - node/install-packages:
          app-dir: tdrs-frontend
          cache-path: ~/.cache
          pkg-manager: yarn
      - run:
          name: "Run ESLint"
          command: "cd tdrs-frontend; yarn lint"
      - run:
          name: "Run Pa11y Accessibility Tests"
          command: "cd tdrs-frontend; yarn test:accessibility"
      - run:
          name: "Run Jest Unit Tests"
          command: "cd tdrs-frontend; yarn test:ci"
      - run:
          name: "Upload Frontend Coverage Report to CodeCov If Target Branch"
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ] ; then
              cd tdrs-frontend; bash <(curl -s https://codecov.io/bash)  -f ./coverage/lcov.info -F main-frontend
            elif [ "$CIRCLE_BRANCH" == "raft-tdp-main" ] ; then
              cd tdrs-frontend; bash <(curl -s https://codecov.io/bash)  -f ./coverage/lcov.info -F dev-frontend
            fi
      - run:
          name: "Run Cypress Integration Tests"
          command: "cd tdrs-frontend; yarn cy:run:ci"
      - run:
          name:  "Test: Execute Frontend  OWASP ZAP Vulnerability Scan"
          command: "cd tdrs-frontend; ./zap-scanner.sh"
      - store_artifacts:
          path: tdrs-frontend/reports/owasp_report.html

  deploy-dev:
    working_directory: ~/tdp-deploy
    docker:
      - image: circleci/python:3.8
        user: root
    steps:
      - checkout
      - sudo-check
      - cf-check
      - login-cloud-dot-gov
      - deploy-frontend
      - deploy-backend

  deploy-staging:
    working_directory: ~/tdp-deploy
    docker:
      - image: circleci/python:3.8
        user: root
    steps:
      - checkout
      - sudo-check
      - cf-check
      - login-cloud-dot-gov:
          cf-password: CF_PASSWORD_STAGING
          cf-space: tanf-staging
          cf-username: CF_USERNAME_STAGING
      - deploy-frontend:
          backend-appname: tdp-backend-staging
          frontend-appname: tdp-frontend-staging
      - deploy-backend:
          backend-appname: tdp-backend-staging

  deploy-prod:
    working_directory: ~/tdp-deploy
    docker:
      - image: circleci/python:3.8
        user: root
    steps:
      - checkout
      - sudo-check
      - cf-check
      - login-cloud-dot-gov:
          cf-password: CF_PASSWORD_PROD
          cf-space: tanf-prod
          cf-username: CF_USERNAME_PROD
      - deploy-frontend:
          backend-appname: tdp-backend-prod
          frontend-appname: tdp-frontend-prod
      - deploy-backend:
          backend-appname: tdp-backend-prod

workflows:
  build-and-test:
    jobs:
      - test-backend
      - test-frontend
      - deploy-dev:
          requires:
            - test-backend
            - test-frontend
          filters:
            branches:
              only:
                - raft-review
                - raft-tdp-main
