# Local version of Docker compose, using the localdev docker build target
# instead and additionally mounts node_modules for faster builds
version: "3.4"

services:
  tdp-frontend:
    build:
      context: .
      target: localdev
    command: yarn start
    volumes:
      - /home/node/app/node_modules
