name: Run Checks based on label
on:
  pull_request:
    types:
    - labeled
    - opened
    - synchronize
    - reopened
jobs:
  pr_labeled_checks:
    runs-on: ubuntu-latest
    name: Initiate checks in circleci
    steps:
    - uses: actions/checkout@v2
    - name: Extract OWASP Label
      id: extract-owasp-label
      run: |
        echo "::set-output name=OWASP::${{ contains( github.event.pull_request.labels.*.name, 'run-owasp') }}"
    - name: Extract Frontend Label
      id: extract-frontend-label
      run: |
        echo "::set-output name=FRONTEND::${{ contains( github.event.pull_request.labels.*.name, 'run-frontend') }}"
    - name: Extract Backend Label
      id: extract-backend-label
      run: |
        echo "::set-output name=BACKEND::${{ contains( github.event.pull_request.labels.*.name, 'run-backend') }}"
    - name: Extract Pa11y Label
      id: extract-pa11y-label
      run: |
        echo "::set-output name=PA11y::${{ contains( github.event.pull_request.labels.*.name, 'run-pa11y') }}"
    - name: Extract QASP Label
      id: extract-qasp-label
      run: |
        echo "::set-output name=QASP::${{ contains( github.event.pull_request.labels.*.name, 'run-qasp') }}"
    - name: Circle CI checks Trigger
      id: curl-circle-ci
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: raft-tech/TANF-app
        branch: ${{ github.head_ref }}
        payload: |
          {
            "frontend": '${{steps.extract-frontend-label.outputs.FRONTEND}}',
            "backend": '${{steps.extract-frontend-label.outputs.BACKEND}}',
            "pa11y": '${{steps.extract-pa11y-label.outputs.PA11Y}}',
            "owasp": '${{steps.extract-owasp-label.outputs.OWASP}}',
            "qasp": '${{steps.extract-qasp-label.outputs.QASP}}'
          }

