name: Run Checks based on label
on:
  pull_request:
    types:
    - labeled
    - unlabeled
    - opened
    - synchronize
    - reopened
jobs:
  pr_labeled_checks:
    if: github.repository == 'raft-tech/TANF-app' || github.repository == 'HHS/TANF-app'
    runs-on: ubuntu-latest
    name: Initiate checks in circleci
    steps:
    - uses: actions/checkout@v2

    - name: Extract OWASP Label
      id: extract-owasp-label
      run: |
        echo "::set-output name=OWASP::${{ contains( github.event.pull_request.labels.*.name, 'run-owasp') }}"

    - name: Extract Pa11y Label
      id: extract-pa11y-label
      run: |
        echo "::set-output name=PA11y::${{ contains( github.event.pull_request.labels.*.name, 'run-pa11y') }}"

    - name: Extract QASP Label
      id: extract-qasp-label
      run: |
        echo "::set-output name=QASP::${{ contains( github.event.pull_request.labels.*.name, 'QASP Review') }}"

    - name: Extract frontend Label
      id: extract-frontend-label
      run: |
        echo "::set-output name=FRONTEND::${{ contains( github.event.pull_request.labels.*.name, 'frontend') }}"

    - name: Extract backend Label
      id: extract-backend-label
      run: |
        echo "::set-output name=BACKEND::${{ contains( github.event.pull_request.labels.*.name, 'backend') }}"

    - name: Circle CI checks Trigger
      id: curl-circle-ci
      if: |
        steps.extract-backend-label.outputs.BACKEND == true ||
        steps.extract-frontend-label.outputs.FRONTEND == true ||
        steps.extract-qasp-label.outputs.QASP == true
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        payload: |
          {
            "backend": ${{steps.extract-backend-label.outputs.BACKEND}},
            "frontend": ${{steps.extract-frontend-label.outputs.FRONTEND}},
            "owasp": ${{steps.extract-owasp-label.outputs.OWASP}},
            "pa11y": ${{steps.extract-pa11y-label.outputs.PA11Y}},
            "qasp": ${{steps.extract-qasp-label.outputs.QASP}}
          }
