###########################################################################
# GitHub Action Workflow
# On assignment of the explicit label `Deploy with CircleCI` to an open PR
# in GitHub this action will trigger a deploy job within CircleCI for the
# branch defined in the given PR.
#
# Step 0: Checkout latest commit on current branch
#
name: Run Checks based on label
on: [ push, pull_request ]
jobs:
  pr_labeled_deployment:
    runs-on: ubuntu-latest
    name: Initiate checks in circleci
    steps:
    - uses: actions/checkout@v2
    - name: Extract OWASP Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-owasp')
      run: |
        echo "::set-output name=OWASP::true"
        
    - name: Extract Frontend Label
      id: extract-frontend-label
      if: contains( github.event.pull_request.labels.*.name, 'run-frontend')
      run: |
        echo "::set-output name=FRONTEND::true"

    - name: Extract Backend Label
      id: extract-backend-label
      if: contains( github.event.pull_request.labels.*.name, 'run-backend')
      run: |
        echo "::set-output name=BACKEND::true"

    - name: Extract Pa11y Label
      id: extract-pa11y-label
      if: contains( github.event.pull_request.labels.*.name, 'run-pa11y')
      run: |
        echo "::set-output name=PA11y::true"

    - name: Extract QASP Label
      id: extract-qasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-qasp')
      run: |
        echo "::set-output name=PA11Y::true"

    - name: Circle CI checks Trigger
      id: curl-circle-ci
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: raft-tech/TANF-app
        branch: ${{ github.head_ref }}
        payload: |
          {
            "frontend": '${{steps.extract-frontend-label.outputs.FRONTEND}}',
            "backend": '${{steps.extract-frontend-label.outputs.BACKEND}}',
            "pa11y": '${{steps.extract-pa11y-label.outputs.PA11Y}}',
            "owasp": '${{steps.extract-owasp-label.outputs.OWASP}}',
            "qasp": '${{steps.extract-qasp-label.outputs.QASP}}'
          }

