name: Nightly OWASP scan
on:
  schedule:
    - cron: '* * * * *'
jobs:
  nightly_owasp_scan:
    name: Initiate Nightly OWASP scan in Circle CI
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Circle CI Nightly OWASP scan
      id: curl-circle-ci
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        payload: |
          {
            "run_nightly_owasp_scan": true
          }