name: Run OWASP scan when a PR moves into QASP Review
on:
  pull_request:
    types:
    - labeled
    - synchronize
    - reopened
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  pr_labeled_checks:
    if: github.repository == 'raft-tech/TANF-app' || github.repository == 'HHS/TANF-app'
    runs-on: ubuntu-latest
    name: Initiate checks in circleci
    env:
      HAS_QASP_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'QASP Review') }}
    steps:
    - name: DEBUG
      run: echo "${{env.HAS_QASP_LABEL}}"
    - name: Circle CI checks Trigger
      id: curl-circle-ci
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        payload: |
          {
            "run_owasp_scan": "${{env.HAS_QASP_LABEL}}"
          }
